### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by rogge-zheng** [go-chassis/go-chassis-cloud#7]
# github.com/go-chassis/go-chassis-cloud/pkg/client/cse
/usr/local/gomod/pkg/mod/github.com/go-chassis/go-chassis-cloud@v2.1.0+incompatible/pkg/client/cse/client.go:38:3: unknown field 'SSLEnabled' in struct literal of type httpclient.Options
make: *** [build] Error 2

**Comment by tianxiaoliang** [comment]
使用2.1.0配套最新的go chassis

问题已修复
https://github.com/go-chassis/go-chassis-cloud/pull/6/commits/a842f5037ac0d08e5b17fb815c3ee800ee577735
